[project]
name = "fly-stick"
version = "0.1.0"
description = "A Python library for game controller input handling"
readme = "README.md"
authors = [
    { name = "windlx", email = "1418043337@qq.com" },
]
requires-python = ">=3.10"
dependencies = [
    "rich>=15.0.0",
    "toml>=0.10.2",
]


[tool.maturin]
module-name = "fly_stick._core"
python-packages = [
    "fly_stick",
]
python-source = "src"

[build-system]
requires = [
    "maturin>=1.0,<2.0",
]
build-backend = "maturin"

[dependency-groups]
dev = [
    "mypy>=2.0.0",
    "pytest>=9.0.2",
    "rich>=14.0.0",
    "ruff>=0.11.0",
]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "SIM", "UP"]

[tool.mypy]
python_version = "3.10"
strict = true
files = ["src/fly_stick", "tests"]
