device_name = "Microsoft Xbox Series S|X Controller"
author = "WindLX"
created = "2025-06-16"
description = "Microsoft Xbox Series S|X Controller Device Description File"

# Axes
[[axes]]
code = 0
alias = "ABS_X"

[[axes]]
code = 1
alias = "ABS_Y"

[[axes]]
code = 2
alias = "ABS_RZ"

[[axes]]
code = 3
alias = "ABS_RX"

[[axes]]
code = 4
alias = "ABS_RY"

[[axes]]
code = 5
alias = "ABS_RZ"

# Buttons
[[buttons]]
code = 167
alias = "BTN_UPLOAD"

[[buttons]]
code = 304
alias = "BTN_A"

[[buttons]]
code = 305
alias = "BTN_B"

[[buttons]]
code = 307
alias = "BTN_X"

[[buttons]]
code = 308
alias = "BTN_Y"

[[buttons]]
code = 310
alias = "BTN_LB"

[[buttons]]
code = 311
alias = "BTN_RB"

[[buttons]]
code = 314
alias = "BTN_START"

[[buttons]]
code = 315
alias = "BTN_MENU"

[[buttons]]
code = 316
alias = "BTN_XBOX"

[[buttons]]
code = 317
alias = "BTN_Z"

[[buttons]]
code = 318
alias = "BTN_RZ"

# Hats
[[hats]]
code = 16
alias = "ABS_HAT0X"

[[hats]]
code = 17
alias = "ABS_HAT0Y"
